### PR TITLE
Invoices

### PR DESCRIPTION
**Pull request by mikeyduece**
Let me know what you think about this(ie inheritance)

### CODE REVIEW

**Comment by dphilla** [comment]
Looks good! I'll be submitting that PR for SalesAnalyst later tonight or tomorrow night.

**Comment by mikeyduece** [comment]
https://giphy.com/gifs/PhKhSXofSAm3e/html5

**Comment by mikeyduece** [comment]
http://gph.is/2cLrLbn

**Comment by mikeyduece** [comment]
Lame, that link was supposed to show gif, lol. Noice man. I'm gonna get started on the math methods for the rest of iteration 2. I'm going to have them in a temp file that we can add where ever later.

**Pull request merged**
